"wwwwwwwwwwwwwww",
"w             w",
"w           w w",
"w          w  w",
"w         w   w",
"w             w",
"w  w      w   w",
"w             w",
"w            ww",
"w   w         w",
"wwwwwwwwwwwwwww"
